# Generated by Django 5.2.7 on 2025-11-10 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_alter_content_content'),
        ('leaveMeg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=800, verbose_name='留言内容')),
                ('date', models.DateField(verbose_name='留言时间')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.user', verbose_name='用户id')),
            ],
        ),
    ]
