# Generated by Django 5.2.7 on 2025-11-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveMeg', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='留言时间'),
        ),
    ]
