# Generated by Django 4.1.5 on 2025-11-12 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_user_email'),
        ('leaveMeg', '0003_alter_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavemeg',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='index.user', verbose_name='用户id'),
            preserve_default=False,
        ),
    ]
