# Generated by Django 5.2.7 on 2025-11-13 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_user_email'),
        ('leaveMeg', '0004_leavemeg_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500, verbose_name='评论内容')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='index.content', verbose_name='关联文章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.user', verbose_name='关联用户')),
            ],
        ),
    ]
