# Generated by Django 5.2.7 on 2025-11-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='headPic/', verbose_name='头像')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('role', models.IntegerField(choices=[(1, '管理员'), (2, '普通用户')], default=2, verbose_name='权限')),
            ],
        ),
    ]
