# Generated by Django 5.2.7 on 2025-11-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='昵称'),
        ),
    ]
