# Generated by Django 5.2.7 on 2025-11-05 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
