# Generated by Django 5.2.7 on 2025-11-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_remove_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='图片名')),
                ('path', models.CharField(max_length=128, verbose_name='路径')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='上传世界')),
            ],
        ),
    ]
