# Generated by Django 5.2.7 on 2025-11-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='图片描述'),
        ),
    ]
