# Generated by Django 5.2.7 on 2025-11-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_pic_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('tag', models.IntegerField(choices=[(1, '# 科技'), (2, '# 娱乐'), (3, '# 生活'), (4, '# 学习'), (5, '# 分享'), (6, '# 游戏'), (7, '# 小说'), (8, '# 讨论')], default=8, verbose_name='标签')),
                ('content', models.TextField(verbose_name='内容')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('cover_img', models.ImageField(blank=True, null=True, upload_to='cover/', verbose_name='封面')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('is_top', models.SmallIntegerField(choices=[(1, '置顶'), (2, '无')], default=2, verbose_name='是否置顶')),
                ('look_count', models.IntegerField(default=0, verbose_name='浏览量')),
            ],
        ),
        migrations.AlterField(
            model_name='pic',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像'),
        ),
    ]
