# Generated by Django 5.2.7 on 2025-11-08 02:29

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_content_alter_pic_date_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content',
            field=mdeditor.fields.MDTextField(verbose_name='内容'),
        ),
    ]
