# Generated by Django 5.2.7 on 2025-11-08 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_alter_content_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
    ]
