# Generated by Django 5.2.7 on 2025-11-08 03:24

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_alter_content_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
