# Generated by Django 5.2.7 on 2025-11-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_alter_content_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.IntegerField(choices=[(1, '# 科技'), (2, '# 娱乐'), (3, '# 生活'), (4, '# 学习'), (5, '# 分享'), (6, '# 游戏'), (7, '# 小说'), (8, '# 讨论')], default=8, verbose_name='标签')),
            ],
        ),
    ]
