# Generated by Django 5.2.7 on 2025-11-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=32, verbose_name='标签'),
        ),
    ]
