# Generated by Django 5.2.7 on 2025-11-11 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_alter_tag_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='tag',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='index.tag', verbose_name='标签'),
        ),
    ]
