# Generated by Django 5.2.7 on 2025-11-11 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
