# Generated by Django 5.2.7 on 2025-11-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_remove_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=64, null=True, verbose_name='邮箱'),
        ),
    ]
