# Generated by Django 5.2.7 on 2025-11-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='comment',
            field=models.IntegerField(default=0, verbose_name='评论量'),
        ),
    ]
