# Generated by Django 5.2.7 on 2025-11-13 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0016_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=64, verbose_name='版本号')),
                ('content', models.CharField(max_length=1024, verbose_name='更新内容')),
                ('time', models.DateTimeField(verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='SiteInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents_count', models.IntegerField(verbose_name='文章访客量')),
                ('site_count', models.IntegerField(verbose_name='网站访客量')),
                ('site_meg', models.CharField(max_length=2048, verbose_name='博客公告')),
                ('signature', models.CharField(max_length=648, verbose_name='个性签名')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.user', verbose_name='管理员id')),
            ],
        ),
    ]
